import { ServiceConfig } from '../types';

export const services: ServiceConfig[] = [
    {
        id: 'crop-service',
        name: 'Crop Service',
        environments: [
            { name: 'Dev1', url: 'https://cropservice.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://cropservice-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://cropservice-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://cropservice.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://cropservice.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://cropservice.k8s.growsphere.netafim.cn/health' },
            { name: 'China Stag', url: 'https://cropservice-stag.k8s.growsphere.netafim.cn/health' },
        ],
    },
    {
        id: 'data-api',
        name: 'Data API',
        environments: [
            { name: 'Dev1', url: 'https://dataapi-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://dataapi-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://dataapi-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://dataapi-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://dataapi.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://dataapi.k8s.growsphere.netafim.cn/health' },
            { name: 'China Stag', url: 'https://dataapi-stag.k8s.growsphere.netafim.cn/health' },
        ],
    },
    {
        id: 'account-management',
        name: 'Account Management',
        environments: [
            { name: 'Dev1', url: 'https://accountmanagement-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://accountmanagement-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://accountmanagement-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://accountmanagement-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://accountmanagement.k8s.growsphere.netafim.com/health' },
        ],
    },
    {
        id: 'mobile-bff',
        name: 'Mobile BFF',
        environments: [
            { name: 'Dev1', url: 'https://mobilebff-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://mobilebff-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://mobilebff-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://mobilebff-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://mobilebff.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://mobilebff.k8s.growsphere.netafim.cn/health' },
            { name: 'China Stag', url: 'https://mobilebff-stag.k8s.growsphere.netafim.cn/health' },
        ],
    },
    {
        id: 'graph-api',
        name: 'Graph API',
        environments: [
            { name: 'Dev1', url: 'https://dev1-netbeatvx-graphapi-app-weu.azurewebsites.net/health' },
            { name: 'Dev2', url: 'https://dev2-netbeatvx-graphapi-app-weu.azurewebsites.net/health' },
            { name: 'QA1', url: 'https://qa1-netbeatvx-graphapi-app-weu.azurewebsites.net/health' },
            { name: 'STAG', url: 'https://stag-netbeatvx-graphapi-app-weu.azurewebsites.net/health' },
            { name: 'PROD', url: 'https://prod-netbeatvx-graphapi-app-weu.azurewebsites.net/health' },
            { name: 'China Prod', url: 'https://app-graphapi-prod-china.chinacloudsites.cn/health' },
            { name: 'China Stag', url: 'https://app-graphapi-stag-china.chinacloudsites.cn/health' },
        ],
    },
    {
        id: 'timeseries-api',
        name: 'Timeseries API',
        environments: [
            { name: 'Dev1', url: 'https://timeseriesapi-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://timeseriesapi-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://timeseriesapi-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://timeseriesapi-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://timeseriesapi.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://timeseriesapi.k8s.growsphere.netafim.cn/health' },
            { name: 'China Stag', url: 'https://timeseriesapi-stag.k8s.growsphere.netafim.cn/health' },
        ],
    },
    {
        id: 'irrigation-manager',
        name: 'Irrigation Manager',
        environments: [
            { name: 'Dev1', url: 'https://irrigationmanager-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://irrigationmanager-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://irrigationmanager-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://irrigationmanager-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://irrigationmanager.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://irrigationmanager.k8s.growsphere.netafim.cn/health' },
            { name: 'China Stag', url: 'https://irrigationmanager-stag.k8s.growsphere.netafim.cn/health' },
        ],
    },
    {
        id: 'device-state-manager',
        name: 'Device State Manager',
        environments: [
            { name: 'Dev1', url: 'https://devicestatemanager-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://devicestatemanager-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://devicestatemanager-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://devicestatemanager-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://devicestatemanager.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://devicestatemanager.k8s.growsphere.netafim.cn/health' },
            { name: 'China Stag', url: 'https://devicestatemanager-stag.k8s.growsphere.netafim.cn/health' },
        ],
    },
    {
        id: 'commands-manager',
        name: 'Commands Manager',
        environments: [
            { name: 'Dev1', url: 'https://commandsmanager-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://commandsmanager-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://commandsmanager-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://commandsmanager-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://commandsmanager.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://commandsmanager.k8s.growsphere.netafim.cn/health' },
            { name: 'China Stag', url: 'https://commandsmanager-stag.k8s.growsphere.netafim.cn/health' },
        ],
    },
    {
        id: 'signalr',
        name: 'SignalR',
        environments: [
            { name: 'Dev1', url: 'https://app-netbeatvx-signalr-dev1.azurewebsites.net/health' },
            { name: 'Dev2', url: 'https://app-netbeatvx-signalr-dev2.azurewebsites.net/health' },
            { name: 'QA1', url: 'https://app-netbeatvx-signalr-qa1.azurewebsites.net/health' },
            { name: 'PROD', url: 'https://app-netbeatvx-signalr-prod.azurewebsites.net/health' },
            { name: 'China Prod', url: 'https://app-signalr-prod-china.chinacloudsites.cn/health' },
            { name: 'China Stag', url: 'https://app-signalr-stag-china.chinacloudsites.cn/health' },
        ],
    },
    {
        id: 'api-gateway',
        name: 'API Gateway',
        environments: [
            { name: 'Dev2', url: 'https://apigateway-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://apigateway-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://apigateway-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://apigateway.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://apigateway.k8s.growsphere.netafim.cn/health' },
            { name: 'China Stag', url: 'https://apigateway-stag.k8s.growsphere.netafim.cn/health' },
        ],
    },
    {
        id: 'settings-api',
        name: 'Settings API',
        environments: [
            { name: 'Dev1', url: 'https://settingsapi-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://settingsapi-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://settingsapi-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://settingsapi-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://settingsapi.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://settingsapi.k8s.growsphere.netafim.cn/health' },
            { name: 'China Stag', url: 'https://settingsapi-stag.k8s.growsphere.netafim.cn/health' },
        ],
    },
    {
        id: 'irrigation-api',
        name: 'Irrigation API',
        environments: [
            { name: 'Dev1', url: 'https://irrigation-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://irrigation-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://irrigation-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://irrigation-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://irrigation.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://irrigation.k8s.growsphere.netafim.cn/health' },
            { name: 'China Stag', url: 'https://irrigation-stag.k8s.growsphere.netafim.cn/health' },
        ],
    },
    {
        id: 'report-api',
        name: 'Report API',
        environments: [
            { name: 'Dev1', url: 'https://reportapi-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://reportapi-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://reportapi-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://reportapi-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://prod-netbeatvx-reportapi-app-weu.azurewebsites.net/health' },
            { name: 'China Prod', url: 'https://app-reportapi-prod-china.chinacloudsites.cn/health' },
            { name: 'China Stag', url: 'https://app-reportapi-stag-china.chinacloudsites.cn/health' },
        ],
    },
    {
        id: 'cs-api',
        name: 'CS API',
        environments: [
            { name: 'Dev1', url: 'https://csapi-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://csapi-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://csapi-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://csapi-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://csapi.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://csapi.k8s.growsphere.netafim.cn/health' },
            { name: 'China Stag', url: 'https://csapi-stag.k8s.growsphere.netafim.cn/health' },
        ],
    },
    {
        id: 'weather-forecast',
        name: 'Weather Forecast',
        environments: [
            { name: 'Dev1', url: 'https://weatherforecast-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://weatherforecast-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://weatherforecast-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://weatherforecast-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://weatherforecast.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://weatherforecast.k8s.growsphere.netafim.cn/health' },
            { name: 'China Stag', url: 'https://weatherforecast-stag.k8s.growsphere.netafim.cn/health' },
        ],
    },
    {
        id: 'field-io',
        name: 'FieldIO',
        environments: [
            { name: 'Dev1', url: 'https://fieldio-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://fieldio-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://fieldio-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://fieldio-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://fieldio.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://fieldio.k8s.growsphere.netafim.cn/health' },
            { name: 'China Stag', url: 'https://fieldio-stag.k8s.growsphere.netafim.cn/health' },
        ],
    },
    {
        id: 'remote-sensing',
        name: 'Remote Sensing',
        environments: [
            { name: 'Dev1', url: 'https://remotesensing-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://remotesensing-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://remotesensing-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://remotesensing-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://remotesensing.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://remotesensing.k8s.growsphere.netafim.cn/health' },
            { name: 'China Stag', url: 'https://remotesensing-stag.k8s.growsphere.netafim.cn/health' },
        ],
        // Application Insights App IDs — add more envs as DevOps provides them
        appInsightsIds: {
            PROD: '4154b42d-c60b-4052-8b98-0462a2f445c7',
        },
    },
    {
        id: 'lookup-service',
        name: 'Lookup Service',
        environments: [
            { name: 'Dev1', url: 'https://lookup-dev1.k8s.growsphere.netafim.com/health' },
            { name: 'Dev2', url: 'https://lookup-dev2.k8s.growsphere.netafim.com/health' },
            { name: 'QA1', url: 'https://lookup-qa1.k8s.growsphere.netafim.com/health' },
            { name: 'STAG', url: 'https://lookup-stag.k8s.growsphere.netafim.com/health' },
            { name: 'PROD', url: 'https://lookup.k8s.growsphere.netafim.com/health' },
            { name: 'China Prod', url: 'https://app-lookup-prod-china.chinacloudsites.cn/health' },
            { name: 'China Stag', url: 'https://app-lookup-stag-china.chinacloudsites.cn/health' },
        ],
    },
    {
        id: 'identity-service',
        name: 'Identity Service',
        environments: [
            { name: 'China Prod', url: 'https://app-ids.k8s.growsphere.netafim.cn/.well-known/openid-configuration' },
        ],
    },
    {
        id: 'rsense-adapter',
        name: 'RSense Adapter',
        environments: [
            { name: 'China Stag', url: 'https://rsenseadapter-stag.k8s.growsphere.netafim.cn/health' },
        ],
    },
];
